config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  get '/about', to: 'about#show'

  resources :users, only: [:create] do
    collection do
      root              to: 'users#new'
      get   :register,  to: 'users#new'
      get   :login,     to: 'sessions#new'
      post  :login,     to: 'sessions#create'
      get   :logout,    to: 'sessions#destroy'
    end
  end

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :create, :new]
    resources :sales, only: [:index, :new]
  end

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
    @products = Product.all.order(created_at: :desc)  
    @categories = Category.all
  end
end

app/views/admin/dashboard/show.html.erb
<div class="panel panel-primary dashboard">
  <div class="panel-heading">
    <h2 class="panel-title text-center">Dashboard</h2>
  </div>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class="text-center">Total Products</th>
          <th scope="col" class="text-center">Total Categories</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td scope="row" class="text-center"><%= link_to @products.count, admin_products_path %></td>
          <td scope="row" class="text-center"><%= link_to @categories.count, admin_categories_path %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>