config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  get '/about', to: 'about#show'

  resources :users, only: [:create] do
    collection do
      root              to: 'users#new'
      get   :register,  to: 'users#new'
      get   :login,     to: 'sessions#new'
      post  :login,     to: 'sessions#create'
      get   :logout,    to: 'sessions#destroy'
    end
  end

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :create, :new]
    resources :sales, only: [:index, :new]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_many :products
  
  validates :name, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  http_basic_authenticate_with name: ENV['USERNAME'], password: ENV['PASSWORD']

  # for final project 
  # def index
  #   render json: Category.all, only: [:id, :name ]s
  # end

  def index
    @categories = Category.all 
  end

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to admin_categories_path, notice: 'Category created!'
    else
      render :new
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:id])
    @products = @category.products.order(created_at: :desc)
  end

end

app/views/admin/categories/_category.html.erb
<tr>
  <td>
    <%= link_to category.name, category %>
  </td>
  <td>
    <%= category.products.count %>
  </td>
</tr>

app/views/admin/categories/index.html.erb
<section class="admin-categories-index">

  <header class="page-header">
    <h1>Admin &raquo; All categories</h1>
  </header>

  <div class="well">
    <%= link_to '+ New Category', new_admin_category_path, class: 'btn btn-info' %>
  </div>

  <div class="panel panel-default categories">

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Category</th>
          <th>Total Products</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <%= render 'category', category: category %>
        <% end %>
      </tbody>
    </table>

  </div>

</section>

app/views/admin/categories/new.html.erb
<section class="admin-products-new">

  <header class="page-header">
    <h1>Admin &raquo; New Category</h1>
  </header>

  <div class="well">
    <%= link_to 'All Category', [:admin, :categories], class: 'btn btn-info' %>
  </div>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-1">
    
      <%= form_for [:admin, @category] do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-danger">
            <strong>The following errors prevented saving:</strong>
            <ul>
              <% form.object.errors.full_messages.each do |error| %>
                <li><%= error %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'form-control' %>
        </div>

  
        <%= form.submit 'Create Category', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>

</section>